# Generated by Django 5.2.10 on 2026-03-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Q1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
