# Generated by Django 5.2.10 on 2026-03-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Q1', '0003_author_publisher_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('dob', models.DateField()),
            ],
        ),
    ]
